import './globals.scss'
import NextUiProvider from '@/context/providers/nextUi.provider'
import { Outfit } from 'next/font/google'
import AuthSessionProvider from '@/context/providers/AuthSessionProvider'
import dynamic from 'next/dynamic'
const SWRProvider = dynamic(async () => await import('@/context/providers/swr.provider'), {
  ssr: false
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  weight: ['200', '300', '400', '500', '600', '700']
})

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='es'>
    <body className={outfit.className}>
      <AuthSessionProvider>
        <SWRProvider>
          <NextUiProvider>{children}</NextUiProvider>
        </SWRProvider>
      </AuthSessionProvider>
    </body>
  </html>
)

export default RootLayout
