import './globals.scss'
import NextUiProvider from '@/context/providers/nextUi.provider'
import SWRProvider from '@/context/providers/swr.provider'
import ReduxProvider from '@/context/providers/redux.provider'
import { Outfit } from 'next/font/google'
import AuthSessionProvider from '@/context/providers/AuthSessionProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  weight: ['200', '300', '400', '500', '600', '700']
})

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='es'>
    <body className={outfit.className}>
      <AuthSessionProvider>
        <ReduxProvider>
          <SWRProvider>
            <NextUiProvider>{children}</NextUiProvider>
          </SWRProvider>
        </ReduxProvider>
      </AuthSessionProvider>
    </body>
  </html>
)

export default RootLayout
