import "./globals.scss";
import NextUiProvider from "@/context/providers/nextUi.provider";
import SWRProvider from "@/context/providers/swr.provider";
import ReduxProvider from "@/context/providers/redux.provider";
import { Outfit } from "next/font/google";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={outfit.className}>
        <ReduxProvider>
          <SWRProvider>
            <NextUiProvider>{children}</NextUiProvider>
          </SWRProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
